#!/usr/bin/env python3
"""Generate or verify the public exact-constants appendix from the certificate JSON."""
from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CERT_PATH = ROOT / "certificate" / "certificates" / "universal_contact_bound_certificate.json"
OUT_PATH = ROOT / "proof" / "APPENDIX_A_EXACT_CONSTANTS.md"


def q(value: object) -> str:
    return f"`{value}`"


def exact_summary(value: str, field_path: str, limit: int = 52) -> str:
    """Render short fractions fully and identify very large fractions by exact field."""
    if len(value) <= limit:
        return q(value)
    numerator, denominator = value.split("/", 1)
    return (
        f"certificate field `{field_path}` "
        f"({len(numerator)}-digit numerator / {len(denominator)}-digit denominator)"
    )


def decimal_lower(value: str, digits: int = 24, multiplier: str | None = None) -> str:
    """Return a decimal rounded downward from an exact positive rational."""
    fraction = Fraction(value)
    if multiplier is not None:
        fraction *= Fraction(multiplier)
    scale = 10**digits
    scaled = fraction.numerator * scale // fraction.denominator
    whole, remainder = divmod(scaled, scale)
    return f"{whole}.{remainder:0{digits}d}"


def render() -> str:
    certificate = json.loads(CERT_PATH.read_text(encoding="ascii"))
    theorem = certificate["theorem"]
    partition = certificate["circumradius_partition"]
    lower = certificate["lower_branch"]
    near = certificate["near_Jung_branch"]
    pi_lower = certificate["pi_bounds"]["lower"]

    coefficient_num, coefficient_den = theorem["coefficient_of_pi"].split("/", 1)

    lines: list[str] = [
        "# Appendix A: exact constants and certificate census",
        "",
        "**Document status:** generated from the authoritative machine-readable certificate.",
        "",
        "**Certificate schema:** " + q(certificate["schema"]),
        "",
        "**Source:** " + q("certificate/certificates/universal_contact_bound_certificate.json"),
        "",
        "This file is generated by `proof/generate_exact_constants.py`. Do not edit it by hand.",
        "The exact verifier and certificate JSON remain the proof authority; this appendix is a",
        "human-readable projection of selected theorem-critical fields.",
        "",
        "Very large exact fractions are identified by their JSON field and numerator/denominator",
        "digit counts rather than printed across the page. The full integers remain in the",
        "checksummed certificate. Decimal values marked “lower” are rounded downward from the",
        "corresponding exact rational; lower-row volume decimals also use the certificate's exact",
        "rational lower bound for $\\pi$.",
        "",
        "## Main coefficient",
        "",
        "For every convex body $K\\subset\\mathbb R^3$ of constant width $d>0$, the package",
        "represents the proposed inequality",
        "",
        "$$",
        "\\mathrm{Vol}(K)\\ge",
        f"\\frac{{{coefficient_num}\\pi}}{{{coefficient_den}}}d^3",
        "=" + theorem["coefficient_decimal_lower"] + "\\ldots d^3.",
        "$$",
        "",
        "- Exact coefficient of $\\pi$: " + q(theorem["coefficient_of_pi"]),
        "- Certified decimal lower enclosure: " + q(theorem["coefficient_decimal_lower"]),
        "- Strict gain over the predecessor certificate: "
        + q(theorem["strict_gain_over_previous_lower"]),
        "",
        "## Circumradius split",
        "",
        "| Field | Exact value | Decimal/rendered value |",
        "|---|---:|---:|",
        f"| Split $R_*$ | {q(partition['split'])} | {q(partition['split_decimal'])} |",
        f"| Lower branch | {q('[' + partition['lower_branch'][0] + ', ' + partition['lower_branch'][1] + ']')} | - |",
        f"| Near-Jung branch | {q('[' + partition['near_Jung_branch'][0] + ', ' + partition['near_Jung_branch'][1] + ']')} | - |",
        f"| Gap-free flag | {q(partition['gap_free'])} | - |",
        "",
        "## Lower-circumradius partition",
        "",
        "Each row below records the exact interval, tangency radius, grid-step counts, and",
        "coefficient of $\\pi$. The displayed volume lower is a uniform 18-place certified",
        "decimal lower bound computed from the exact coefficient and the certificate's rational",
        "lower bound for $\\pi$.",
        "",
    ]

    for row in lower["rows"]:
        case = row["case"]
        interval = "[" + row["interval"][0] + ", " + row["interval"][1] + "]"
        volume_lower = decimal_lower(row["coefficient_of_pi"], 18, pi_lower)
        lines.extend(
            [
                f"### Row `{case}`",
                "",
                f"- Circumradius interval: {q(interval)}",
                f"- Tangency radius $s_0$: {q(row['s0'])}",
                f"- Propagation steps: {row['positive_steps']} positive; {row['negative_steps']} negative",
                f"- Exact coefficient of $\\pi$: {q(row['coefficient_of_pi'])}",
                f"- Certified volume lower: {q(volume_lower)}",
            ]
        )
        if "margin_over_theorem_coefficient" in row:
            lines.extend(
                [
                    f"- Margin over theorem coefficient as a coefficient of $\\pi$: "
                    f"{q(row['margin_over_theorem_coefficient'])}",
                    f"- Angular denominator: {row['angle_grid_N']}",
                    f"- Radial denominator: {row['radial_grid']}",
                ]
            )
        lines.append("")

    refined = lower["refined_angular_grid"]
    lines.extend(
        [
            "### Lower-branch summary",
            "",
            f"- Weakest lower-branch row: {q(lower['weakest_row'])}",
            f"- Weakest exact coefficient of $\\pi$: {q(lower['weakest_coefficient_of_pi'])}",
            f"- Refined replacement cells: {refined['cells']}",
            f"- Refined angular denominator: {refined['angle_N']}",
            f"- Refined radial denominator: {refined['radial_grid']}",
            f"- Minimum exact refined-row margin over theorem coefficient: "
            f"{q(refined['minimum_margin_over_theorem'])}",
            f"- Replaced predecessor row: {q(lower['replaced_reference_row'])}",
            "",
            "## Near-Jung fan census",
            "",
            "| Quantity | Integer value |",
            "|---|---:|",
            f"| Fan vertices | {near['fan_reconstruction']['vertices']} |",
            f"| Fan triangular faces | {near['fan_reconstruction']['faces']} |",
            f"| Fan edges | {near['fan_reconstruction']['edges']} |",
            f"| Stabilizer orbits | {near['fan_reconstruction']['orbits']} |",
            f"| Changed vertices | {near['changed_vertices_from_reference']} |",
            f"| Minimum cone determinant | {near['fan_reconstruction']['minimum_cone_determinant']} |",
            "",
            "## Near-Jung exact inequalities",
            "",
            "### Minimum fan margin",
            "",
            "- Exact: "
            + exact_summary(near["minimum_margin"], "near_Jung_branch.minimum_margin"),
            "- Certified decimal lower: " + q(decimal_lower(near["minimum_margin"], 24)),
            "",
            "### Total-deficiency upper bound",
            "",
            "- Exact: "
            + exact_summary(
                near["sharp_total_deficiency_upper"],
                "near_Jung_branch.sharp_total_deficiency_upper",
            ),
            "- Decimal rendering: "
            + q(decimal_lower(near["sharp_total_deficiency_upper"], 24)),
            "",
            "### Determinant-squared lower bound",
            "",
            "- Exact: "
            + exact_summary(
                near["determinant_squared_lower"],
                "near_Jung_branch.determinant_squared_lower",
            ),
            "- Certified decimal lower: "
            + q(decimal_lower(near["determinant_squared_lower"], 24)),
            "",
            "### Reference-fan coefficient",
            "",
            "- Exact: "
            + exact_summary(
                near["reference_fan_coefficient"],
                "near_Jung_branch.reference_fan_coefficient",
            ),
            "- Certified decimal lower: "
            + q(decimal_lower(near["reference_fan_coefficient"], 24)),
            "",
            "### Active-bound census",
            "",
            "| Bound class | Count |",
            "|---|---:|",
        ]
    )
    for key in ("convex", "dominant", "edge", "tie"):
        lines.append(f"| {key} | {near['active_bound_census'][key]} |")

    lemma = near["coordinate_width_lemma"]
    lines.extend(
        [
            "",
            "## Dominant-edge coordinate-width inputs",
            "",
            f"- Distinguished edge: {q(lemma['dominant_edge'])}",
            f"- Axis 0 diagonal bound: {q(lemma['axis0_upper'])}",
            f"- Axis 1 diagonal bound: {q(lemma['axis1_upper'])}",
            f"- Axis 2 diagonal bound: {q(lemma['axis2_upper'])}",
            f"- Positive-definite inverse argument: {lemma['inverse_diagonal_argument']}",
            "",
            "## Core, caps, and universal handoff",
            "",
        ]
    )

    core_fields = [
        (
            "Forced-core lower bound",
            "core_volume_lower",
            "near_Jung_branch.core_volume_lower",
        ),
        (
            "Three-pair cap lower bound",
            "total_cap_lower",
            "near_Jung_branch.total_cap_lower",
        ),
        (
            "Near-Jung volume lower bound",
            "volume_lower",
            "near_Jung_branch.volume_lower",
        ),
        (
            "Near-Jung margin over theorem upper enclosure",
            "margin_over_theorem_upper",
            "near_Jung_branch.margin_over_theorem_upper",
        ),
    ]
    for title, key, field_path in core_fields:
        lines.extend(
            [
                f"### {title}",
                "",
                "- Exact: " + exact_summary(near[key], field_path),
                "- Certified decimal lower: " + q(decimal_lower(near[key], 24)),
                "",
            ]
        )

    lines.extend(["## Coordinate-axis cap pairs", ""])
    for cap in near["cap_pairs"]:
        axis = cap["axis"]
        lines.extend(
            [
                f"### Axis {axis}",
                "",
                "- Coordinate-width-squared lower: "
                + exact_summary(
                    cap["coordinate_width_squared_lower"],
                    f"near_Jung_branch.cap_pairs[{axis}].coordinate_width_squared_lower",
                ),
                "- Coordinate-width lower (certified decimal): "
                + q(decimal_lower(cap["coordinate_width_lower"], 18)),
                "- Pair-cap lower: "
                + exact_summary(
                    cap["pair_cap_lower"],
                    f"near_Jung_branch.cap_pairs[{axis}].pair_cap_lower",
                ),
                "- Pair-cap lower (certified decimal): "
                + q(decimal_lower(cap["pair_cap_lower"], 24)),
                "- Section hull sizes, positive/negative: "
                + q("/".join(str(value) for value in cap["section_hull_sizes"])),
                "",
            ]
        )

    disjointness = near["cross_axis_disjointness"]
    lines.extend(
        [
            "## Cross-axis disjointness",
            "",
            "### Ellipsoid radius-squared upper bound",
            "",
            "- Exact: " + q(disjointness["ellipsoid_radius_squared_upper"]),
            "- Decimal upper rendering: "
            + q(decimal_lower(disjointness["ellipsoid_radius_squared_upper"], 18)),
            "",
            "### Overlap-norm-squared lower bound",
            "",
            "- Exact: "
            + exact_summary(
                disjointness["overlap_norm_squared_lower"],
                "near_Jung_branch.cross_axis_disjointness.overlap_norm_squared_lower",
            ),
            "- Certified decimal lower: "
            + q(decimal_lower(disjointness["overlap_norm_squared_lower"], 18)),
            "",
            "### Strict separation gap",
            "",
            "- Exact: "
            + exact_summary(
                disjointness["strict_gap"],
                "near_Jung_branch.cross_axis_disjointness.strict_gap",
            ),
            "- Certified decimal lower: "
            + q(decimal_lower(disjointness["strict_gap"], 24)),
            "",
            "## Immutable object fingerprints",
            "",
            "### Reference handoff certificate",
            "",
            "```text",
            lower["reference_handoff_certificate_sha256"],
            "```",
            "",
            "### Reference near-Jung fan",
            "",
            "```text",
            near["reference_fan_sha256"],
            "```",
            "",
            "### Adjusted universal fan",
            "",
            "```text",
            near["adjusted_fan_sha256"],
            "```",
            "",
            "## Claim boundary copied from the certificate",
            "",
            "### Certified inside this package",
            "",
        ]
    )
    for item in certificate["claim_boundary"]["certified_inside_package"]:
        lines.append(f"- {item}")
    lines.extend(["", "### Not established", ""])
    for item in certificate["claim_boundary"]["not_established"]:
        lines.append(f"- {item}")
    lines.extend(
        [
            "",
            "## Verification",
            "",
            "Regenerate this appendix deliberately with:",
            "",
            "```sh",
            "python3 proof/generate_exact_constants.py",
            "```",
            "",
            "Verify that it is current without modifying it with:",
            "",
            "```sh",
            "python3 proof/generate_exact_constants.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = (render().rstrip() + "\n").encode("utf-8")
    if args.check:
        if not OUT_PATH.exists() or OUT_PATH.read_bytes() != expected:
            raise SystemExit(f"stale generated exact-constants appendix: {OUT_PATH}")
        print("MINVOL EXACT-CONSTANTS APPENDIX: CURRENT")
    else:
        OUT_PATH.write_bytes(expected)
        print(f"WROTE {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
