#!/usr/bin/env python3
"""Generate and verify paper-facing constants from the exact certificate.

The machine-readable certificate is the numerical source of truth for the
manuscript.  This script writes the small TeX include files used by the paper
and verifies that committed copies remain byte-identical to a fresh rebuild.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from decimal import Decimal, ROUND_HALF_UP, getcontext
from fractions import Fraction
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
CERT = ROOT / "certificate" / "certificates" / "universal_contact_bound_certificate.json"
CONSTANTS = HERE / "certificate_constants.tex"
LOWER_TABLE = HERE / "lower_branch_table.tex"
PAPER = HERE / "contact_geometric_bound.tex"
EXPECTED_SCHEMA = "minvol.universal_contact_bound.v1"
FORBIDDEN_PUBLIC_TOKENS = (
    "PRIVATE WORKING DRAFT",
    "Author list to be finalized",
    "v1.0.0-rc1",
    "UNRELEASED",
)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def decimal_pi(precision: int = 90) -> Decimal:
    """Compute pi deterministically by Machin's formula for display only."""
    getcontext().prec = precision + 20

    def atan(x: Decimal) -> Decimal:
        x2 = x * x
        term = x
        total = term
        denominator = 1
        while True:
            term *= -x2
            denominator += 2
            add = term / Decimal(denominator)
            updated = total + add
            if updated == total:
                return +total
            total = updated

    value = Decimal(16) * atan(Decimal(1) / Decimal(5)) - Decimal(4) * atan(
        Decimal(1) / Decimal(239)
    )
    getcontext().prec = precision
    return +value


def fraction_decimal(value: str, places: int) -> str:
    getcontext().prec = places + 40
    f = Fraction(value)
    rendered = format(Decimal(f.numerator) / Decimal(f.denominator), f".{places + 4}f")
    return fmt_decimal(rendered, places)


def fmt_decimal(value: str, places: int) -> str:
    text = value.strip()
    if "." not in text:
        return text
    whole, fractional = text.split(".", 1)
    return whole + "." + fractional[:places]


def latex_fraction(text: str) -> str:
    if text == "sqrt(6)/4":
        return r"\sqrt6/4"
    f = Fraction(text)
    if f.denominator == 1:
        return str(f.numerator)
    return rf"\frac{{{f.numerator}}}{{{f.denominator}}}"


def latex_interval(interval: list[str]) -> str:
    return rf"$[{latex_fraction(interval[0])},{latex_fraction(interval[1])}]$"


def rounded_volume_decimal(coefficient_of_pi: str, places: int = 15) -> str:
    getcontext().prec = 100
    f = Fraction(coefficient_of_pi)
    value = Decimal(f.numerator) / Decimal(f.denominator) * decimal_pi(90)
    quantum = Decimal(1).scaleb(-places)
    return format(value.quantize(quantum, rounding=ROUND_HALF_UP), f".{places}f")


def macro(name: str, value: str) -> str:
    return rf"\providecommand{{\{name}}}{{{value}}}" + "\n"


def constants_bytes(data: dict) -> bytes:
    theorem = data["theorem"]
    partition = data["circumradius_partition"]
    near = data["near_Jung_branch"]
    cap_pairs = near["cap_pairs"]
    coeff = Fraction(theorem["coefficient_of_pi"])
    split = Fraction(partition["split"])
    cert_hash = sha256(CERT)
    fan = near["fan_reconstruction"]

    widths = [fraction_decimal(p["coordinate_width_lower"], 18) for p in cap_pairs]
    cap_decimals = [fmt_decimal(p["pair_cap_lower_decimal"], 21) for p in cap_pairs]
    hulls = [p["section_hull_sizes"] for p in cap_pairs]

    lines = [
        "% Generated by paper/reconcile_certificate.py.  Do not edit by hand.\n",
        macro("CertificateSchema", data["schema"].replace("_", r"\_")),
        macro("CertificateSha", cert_hash),
        macro("MainNumerator", str(coeff.numerator)),
        macro("MainDenominator", str(coeff.denominator)),
        macro("MainCoefficient", rf"\frac{{{coeff.numerator}\pi}}{{{coeff.denominator}}}"),
        macro("MainCoefficientOfPi", rf"\frac{{{coeff.numerator}}}{{{coeff.denominator}}}"),
        macro("MainDecimal", fmt_decimal(theorem["coefficient_decimal_lower"], 40)),
        macro("GainDecimal", fmt_decimal(theorem["strict_gain_over_previous_lower"], 40)),
        macro("SplitRadius", rf"\frac{{{split.numerator}}}{{{split.denominator}}}"),
        macro("SplitDecimal", fmt_decimal(partition["split_decimal"], 9)),
        macro("DeficiencyDecimal", fmt_decimal(near["sharp_total_deficiency_upper_decimal"], 32)),
        macro("DeterminantDecimal", fmt_decimal(near["determinant_squared_lower_decimal"], 32)),
        macro("FanCoefficientDecimal", fmt_decimal(near["reference_fan_coefficient_decimal"], 28)),
        macro("CoreDecimal", fmt_decimal(near["core_volume_lower_decimal"], 28)),
        macro("CapsDecimal", fmt_decimal(near["total_cap_lower_decimal"], 28)),
        macro("NearDecimal", fmt_decimal(near["volume_lower_decimal"], 28)),
        macro("HandoffMarginDecimal", fmt_decimal(near["margin_over_theorem_upper_decimal"], 28)),
        macro("CrossAxisGapDecimal", fmt_decimal(near["cross_axis_disjointness"]["strict_gap_decimal"], 28)),
        macro("WidthZeroDecimal", widths[0]),
        macro("WidthOneDecimal", widths[1]),
        macro("WidthTwoDecimal", widths[2]),
        macro("CapZeroDecimal", cap_decimals[0]),
        macro("CapOneDecimal", cap_decimals[1]),
        macro("CapTwoDecimal", cap_decimals[2]),
        macro("HullZeroPlus", str(hulls[0][0])),
        macro("HullZeroMinus", str(hulls[0][1])),
        macro("HullOnePlus", str(hulls[1][0])),
        macro("HullOneMinus", str(hulls[1][1])),
        macro("HullTwoPlus", str(hulls[2][0])),
        macro("HullTwoMinus", str(hulls[2][1])),
        macro("FanVertices", f"{fan['vertices']:,}".replace(",", r"{,}")),
        macro("FanFaces", f"{fan['faces']:,}".replace(",", r"{,}")),
        macro("FanEdges", f"{fan['edges']:,}".replace(",", r"{,}")),
        macro("FanOrbits", f"{fan['orbits']:,}".replace(",", r"{,}")),
        macro("ChangedVertices", f"{near['changed_vertices_from_reference']:,}".replace(",", r"{,}")),
        macro("FanMarginDecimal", fmt_decimal(near["minimum_margin_decimal"], 40)),
    ]
    return "".join(lines).encode("ascii")


def lower_table_bytes(data: dict) -> bytes:
    rows = data["lower_branch"]["rows"]
    lines = [
        "% Generated by paper/reconcile_certificate.py.  Do not edit by hand.\n",
        r"\begingroup" + "\n",
        r"\renewcommand{\arraystretch}{1.55}" + "\n",
        r"\setlength{\extrarowheight}{1.5pt}" + "\n",
        r"\begin{longtable}{@{}lll r@{}}" + "\n",
        r"\caption{Gap-free lower-circumradius certificate.  The final column is the displayed width-normalized volume coefficient; exact coefficients of $\pi$ are stored in the certificate JSON.}\label{tab:lower-partition}\\" + "\n",
        r"\toprule" + "\n",
        r"Case & Circumradius interval & Exact mechanism & Volume lower bound\\" + "\n",
        r"\midrule" + "\n",
        r"\endfirsthead" + "\n",
        r"\toprule" + "\n",
        r"Case & Circumradius interval & Exact mechanism & Volume lower bound\\" + "\n",
        r"\midrule" + "\n",
        r"\endhead" + "\n",
        r"\midrule" + "\n",
        r"\multicolumn{4}{r}{Continued on next page}\\" + "\n",
        r"\endfoot" + "\n",
        r"\bottomrule" + "\n",
        r"\endlastfoot" + "\n",
    ]
    for row in rows:
        case = row["case"]
        if case == "0":
            mechanism = "analytic tangent bound"
        elif case.startswith("O3A1R"):
            mechanism = "doubled angular grid"
        else:
            mechanism = "exact radial caps"
        decimal = rounded_volume_decimal(row["coefficient_of_pi"], 15)
        if case == data["lower_branch"]["weakest_row"]:
            case_tex = rf"\textbf{{\texttt{{{case}}}}}"
            decimal_tex = rf"\textbf{{{decimal}}}"
        else:
            case_tex = rf"\texttt{{{case}}}"
            decimal_tex = decimal
        lines.append(
            f"{case_tex} & {latex_interval(row['interval'])} & {mechanism} & ${decimal_tex}$\\\\\n"
        )
    lines.append(r"\end{longtable}" + "\n")
    lines.append(r"\endgroup" + "\n")
    return "".join(lines).encode("ascii")


def validate_data(data: dict) -> None:
    if data.get("schema") != EXPECTED_SCHEMA:
        raise SystemExit(f"unexpected certificate schema: {data.get('schema')!r}")
    theorem = data["theorem"]
    if theorem["coefficient_of_pi"] != "26220940089713/200000000000000":
        raise SystemExit("unexpected theorem coefficient")
    if data["circumradius_partition"]["split"] != "305695601/500000000":
        raise SystemExit("unexpected circumradius split")
    if data["lower_branch"]["weakest_row"] != "O3B02":
        raise SystemExit("unexpected lower-branch bottleneck")
    if not data["circumradius_partition"]["gap_free"]:
        raise SystemExit("circumradius partition is not gap-free")
    if len(data["near_Jung_branch"]["cap_pairs"]) != 3:
        raise SystemExit("expected three antipodal cap pairs")


def validate_paper_source() -> None:
    text = PAPER.read_text(encoding="utf-8")
    for token in FORBIDDEN_PUBLIC_TOKENS:
        if token in text:
            raise SystemExit(f"paper contains private or excluded token: {token!r}")
    required = (
        r"\input{certificate_constants.tex}",
        r"\input{lower_branch_table.tex}",
        r"\MainCoefficient",
        r"\CertificateSha",
        r"\newcommand{\releaseversion}{v1.0.0}",
        r"\newcommand{\releasedate}{September 26, 2026}",
        r"releases/tag/v1.0.0",
    )
    for token in required:
        if token not in text:
            raise SystemExit(f"paper is missing required generated token: {token}")
    if re.search(r"26220940089713|305695601|0\.411877563780302", text):
        raise SystemExit("paper hard-codes a certificate-critical number outside generated TeX")


def process(path: Path, expected: bytes, check: bool) -> None:
    if check:
        if not path.exists() or path.read_bytes() != expected:
            raise SystemExit(f"paper include is stale: {path.relative_to(ROOT)}")
    else:
        path.write_bytes(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="rewrite generated TeX includes")
    parser.add_argument("--check", action="store_true", help="verify without modifying files")
    args = parser.parse_args()
    if args.write and args.check:
        raise SystemExit("choose either --write or --check")
    check = not args.write
    data = json.loads(CERT.read_text(encoding="utf-8"))
    validate_data(data)
    process(CONSTANTS, constants_bytes(data), check)
    process(LOWER_TABLE, lower_table_bytes(data), check)
    validate_paper_source()
    print("MINVOL PAPER-CERTIFICATE RECONCILIATION: PASS")


if __name__ == "__main__":
    main()
